from django.db import models

class CoachesLateness(models.Model):
    case_owner_id = models.IntegerField(unique=True, blank=True, null=True)
    caseowner = models.TextField(db_column='CaseOwner', primary_key=True)
    phone = models.TextField(db_column='Phone', blank=True, null=True)
    lastsubdate = models.DateField(db_column='LastSubDate', blank=True, null=True)
    elapseddays = models.IntegerField(db_column='ElapsedDays', blank=True, null=True)
    evidence_accepted = models.IntegerField(db_column='Evidence Accepted', blank=True, null=True)
    evidence_referred = models.IntegerField(db_column='Evidence Referred', blank=True, null=True)
    total_evidence = models.IntegerField(db_column='Total Evidence', blank=True, null=True)
    completed_sessions = models.IntegerField(db_column='Completed Sessions', blank=True, null=True)
    completed_sessions_hours = models.DecimalField(db_column='Completed Sessions Hours', max_digits=10, decimal_places=2, blank=True, null=True)
    cancelled_sessions = models.IntegerField(db_column='Cancelled Sessions', blank=True, null=True)
    nearest_appointment = models.DateField(db_column='Nearest Appointment', blank=True, null=True)
    with_student = models.TextField(db_column='With Student', blank=True, null=True)
    last_snapshot_date = models.TextField(db_column='Last Snapshot Date', blank=True, null=True)
    total_learners = models.IntegerField(db_column='Total Learners', blank=True, null=True)
    recent_submitters = models.IntegerField(db_column='Recent Submitters', blank=True, null=True)
    pending = models.IntegerField(db_column='Pending', blank=True, null=True)
    today = models.IntegerField(db_column='Today', blank=True, null=True)
    field_2 = models.IntegerField(db_column='-2', blank=True, null=True)
    field_3 = models.IntegerField(db_column='-3', blank=True, null=True)
    yesterday = models.IntegerField(db_column='Yesterday', blank=True, null=True)
    field_4 = models.IntegerField(db_column='-4', blank=True, null=True)
    field_5 = models.IntegerField(db_column='-5', blank=True, null=True)
    field_6 = models.IntegerField(db_column='-6', blank=True, null=True)
    field_7 = models.IntegerField(db_column='-7', blank=True, null=True)
    last_week_pending = models.IntegerField(db_column='Last Week Pending', blank=True, null=True)
    last_week_pr = models.IntegerField(db_column='Last Week PR', blank=True, null=True)
    field_second_week_pr = models.IntegerField(db_column='-Second Week PR', blank=True, null=True)
    field_third_week_pr = models.IntegerField(db_column='-Third Week PR', blank=True, null=True)
    field_fourth_week_pr = models.IntegerField(db_column='- Fourth Week PR', blank=True, null=True)
    total_pr_done_old_for_last_4_weeks = models.IntegerField(db_column='Total PR Done+Old for Last 4 Weeks', blank=True, null=True)
    acutally_done_for_last_4_weeks = models.IntegerField(db_column='Acutally Done for Last 4 Weeks', blank=True, null=True)
    total_pr_required_for_last_4_weeks = models.IntegerField(db_column='Total PR Required for Last 4 Weeks', blank=True, null=True)
    overall_pr_required = models.IntegerField(db_column='Overall (PR) Required', blank=True, null=True)
    overall_pr_behind = models.IntegerField(db_column='Overall (PR) Behind', blank=True, null=True)
    overall_pr_completion_rate = models.TextField(db_column='Overall (PR) Completion Rate', blank=True, null=True)
    overall_pr_completed = models.IntegerField(db_column='Overall (PR) Completed', blank=True, null=True)
    required_pr = models.IntegerField(db_column='Required PR', blank=True, null=True)
    completed_pr = models.IntegerField(db_column='Completed PR', blank=True, null=True)
    still_inprogress_pr = models.IntegerField(db_column='Still Inprogress PR', blank=True, null=True)
    unscheduled_overdue_pr = models.IntegerField(db_column='UnScheduled Overdue PR', blank=True, null=True)
    scheduled_for_the_next_pr_field = models.DecimalField(db_column='Scheduled for the next PR%%', max_digits=10, decimal_places=5, blank=True, null=True)
    scheduled_overdue_pr = models.IntegerField(db_column='Scheduled Overdue PR', blank=True, null=True)
    otjh_ontrack_0_field = models.IntegerField(db_column='OTJH OnTrack 10%%', blank=True, null=True)
    otjh_need_attention_20_40_field = models.IntegerField(db_column='OTJH Need Attention 11-25%%', blank=True, null=True)
    otjh_at_risk_40_field = models.IntegerField(db_column='OTJH At Risk  25%%', blank=True, null=True)
    total_pr_required_for_last_8_weeks = models.IntegerField(db_column='Total PR Required for Last 8 Weeks', blank=True, null=True)
    total_pr_done_old_for_last_8_weeks = models.IntegerField(db_column='Total PR Done+Old for Last 8 Weeks', blank=True, null=True)
    acutally_done_pr_for_last_8_weeks = models.IntegerField(db_column='Acutally Done(PR) for Last 8 Weeks', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'coaches_lateness'

class CoachSummary(models.Model):
    coach_name = models.TextField(primary_key=True)
    week_1_expected = models.TextField(blank=True, null=True)
    week_1_present = models.TextField(blank=True, null=True)
    week_1_absent = models.IntegerField(blank=True, null=True)
    week_1_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week1_company = models.TextField(db_column='week1/ company', blank=True, null=True)
    week_2_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week2_company = models.TextField(db_column='week2/ company', blank=True, null=True)
    week_3_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week3_company = models.TextField(db_column='week3/ company', blank=True, null=True)
    week_4_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week4_company = models.TextField(db_column='week4/ company', blank=True, null=True)
    week_5_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week5_company = models.TextField(db_column='week5/ company', blank=True, null=True)
    week_6_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week6_company = models.TextField(db_column='week6/ company', blank=True, null=True)
    week_7_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week7_company = models.TextField(db_column='week7/ company', blank=True, null=True)
    week_8_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week8_company = models.TextField(db_column='week8/ company', blank=True, null=True)
    week_9_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week9_company = models.TextField(db_column='week9/ company', blank=True, null=True)
    week_10_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)
    week10_company = models.TextField(db_column='week10/ company', blank=True, null=True)
    students_count = models.IntegerField(blank=True, null=True)
    last_10_weeks_absence_ratio = models.DecimalField(max_digits=6, decimal_places=3, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'coach_summary'


